### ISSUE TITLE
An error occurrect

### ISSUE THREAD

**Issue by nick71223** [JosephZoeller/FileMonolith#1]

**Comment by nick71223** [comment]
i fixed the issue i was having

**Comment by morbidslinky** [comment]
Could you describe the issue and how you resolved it? For posterity

**Comment by nick71223** [comment]
not sure why the issue text disappeared, i cant remember the exact error it was but i had to reinstall both games, it just kept saying some script was wrong

**Comment by nick71223** [comment]
i found it, it was this

It says than an error occurred while attempting to transfer data: unable to cast object of type 'System.String' to type 'System.Exception'.

**Comment by morbidslinky** [comment]
Thanks, sounds like you were specifically seeing the error with Archive Transferrer. I'm not sure what that was about either though.
